create database familytrackerdb
CREATE TABLE Users (
    UserID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL, 
    UserRole VARCHAR(30) NOT NULL,  
    Title VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Members (
    MemberID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Relationship VARCHAR(50),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    AddedByUserID INT REFERENCES Users(UserID), 
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UpcomingEvents (
    UpcomingEventID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EventName VARCHAR(100) NOT NULL,
    Description VARCHAR(500), 
    EventDate TIMESTAMP NOT NULL,
    MemberName VARCHAR(100) NOT NULL, 
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RecentEvents (
    RecentEventID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EventName VARCHAR(100) NOT NULL,
    Description VARCHAR(500),
    EventDate TIMESTAMP NOT NULL,
    MemberName VARCHAR(100) NOT NULL,
    LoggedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);